# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 411)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actioncount1 = QtGui.QAction(parent=MainWindow)
        self.actioncount1.setCheckable(True)
        self.actioncount1.setObjectName("actioncount1")
        self.actioncount2 = QtGui.QAction(parent=MainWindow)
        self.actioncount2.setCheckable(True)
        self.actioncount2.setObjectName("actioncount2")
        self.actioncount3 = QtGui.QAction(parent=MainWindow)
        self.actioncount3.setCheckable(True)
        self.actioncount3.setObjectName("actioncount3")
        self.actioncount = QtGui.QAction(parent=MainWindow)
        self.actioncount.setObjectName("actioncount")
        self.menu.addAction(self.actioncount1)
        self.menu.addAction(self.actioncount2)
        self.menu.addAction(self.actioncount3)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actioncount)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "计算"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actioncount1.setText(_translate("MainWindow", "count1"))
        self.actioncount2.setText(_translate("MainWindow", "count2"))
        self.actioncount3.setText(_translate("MainWindow", "count3"))
        self.actioncount.setText(_translate("MainWindow", "count"))
