# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 410)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 22))
        self.menubar.setObjectName("menubar")
        self.menufiie = QtWidgets.QMenu(parent=self.menubar)
        self.menufiie.setObjectName("menufiie")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionopen = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/tys/Desktop/测绘程序设计校赛/图标/11icon/imageres 154.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionopen.setIcon(icon)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/tys/Desktop/测绘程序设计校赛/图标/11icon/shell32 259.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionsave.setIcon(icon1)
        self.actionsave.setObjectName("actionsave")
        self.actionclose = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/tys/Desktop/测绘程序设计校赛/图标/11icon/imageres 085.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionclose.setIcon(icon2)
        self.actionclose.setObjectName("actionclose")
        self.actionmenu_count = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/tys/Desktop/测绘程序设计校赛/图标/11icon/imageres 112.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionmenu_count.setIcon(icon3)
        self.actionmenu_count.setObjectName("actionmenu_count")
        self.actioncuont = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/tys/Desktop/测绘程序设计校赛/图标/11icon/shell32 295.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actioncuont.setIcon(icon4)
        self.actioncuont.setObjectName("actioncuont")
        self.actionopen_2 = QtGui.QAction(parent=MainWindow)
        self.actionopen_2.setIcon(icon)
        self.actionopen_2.setObjectName("actionopen_2")
        self.actionsave_2 = QtGui.QAction(parent=MainWindow)
        self.actionsave_2.setIcon(icon1)
        self.actionsave_2.setObjectName("actionsave_2")
        self.menufiie.addAction(self.actionopen)
        self.menufiie.addAction(self.actionsave)
        self.menufiie.addAction(self.actionclose)
        self.menubar.addAction(self.menufiie.menuAction())
        self.toolBar.addAction(self.actionopen_2)
        self.toolBar.addAction(self.actionsave_2)
        self.toolBar.addAction(self.actioncuont)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menufiie.setTitle(_translate("MainWindow", "fiie"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionclose.setText(_translate("MainWindow", "close"))
        self.actionmenu_count.setText(_translate("MainWindow", "menu_count"))
        self.actioncuont.setText(_translate("MainWindow", "cuont"))
        self.actionopen_2.setText(_translate("MainWindow", "open"))
        self.actionsave_2.setText(_translate("MainWindow", "save"))
